apiVersion: v1
kind: Pod
metadata:
  name: devpod

spec:
  restartPolicy: Always

  containers:
    - name: dev-container
      image: localhost/bootc-dev/dev-container:latest
      stdin: true
      tty: true
      workingDir: /workspace
      env:
        - name: REQUIRE_CUDA
          value: "1"
      resources:
        limits:
          nvidia.com/gpu=all: 1
      volumeMounts:
        - name: workspace
          mountPath: /workspace

    - name: backup-container
      image: localhost/bootc-dev/backup-container:latest
      stdin: true
      tty: true
      workingDir: /workspace
      volumeMounts:
        - name: workspace
          mountPath: /workspace

  volumes:
    - name: workspace
      hostPath:
        path: /var/lib/devpod/workspace
        type: DirectoryOrCreate
