#!/bin/bash
# vllm-bootstrap.sh — write /etc/openclaw-platform/vllm.env with a freshly
# generated API key and sensible defaults if the file does not yet exist.
#
# This is the only place the shared vLLM API key is generated. Once the
# file exists, this script is a no-op (vllm-bootstrap.service has a
# ConditionPathExists=! guard). Operators rotate the key by editing the
# file and restarting vllm.service plus the per-tenant credential entries
# (platformctl credential put <tenant> vllm <new-value>).

set -euo pipefail

ENV_FILE=/etc/openclaw-platform/vllm.env

if [[ -f "${ENV_FILE}" ]]; then
    exit 0
fi

mkdir -p /etc/openclaw-platform

# 32 bytes of urandom, base64'd, stripped of '+/=' for shell-safety.
api_key="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48)"

umask 077
cat >"${ENV_FILE}" <<EOF
# Shared vLLM service configuration. Generated by vllm-bootstrap.service.
# Permissions are 0600 root:root. Distribute the key to tenants only via
# openclaw-broker (platformctl credential put <tenant> vllm <value>).

# Container image. Pin a tag for production.
VLLM_IMAGE=docker.io/vllm/vllm-openai:latest

# Default model. Open-weights, instruction-tuned, fits a single GPU at
# bfloat16. Operators may swap for any vLLM-supported model.
VLLM_MODEL=Qwen/Qwen2.5-7B-Instruct

# Inference quotas. max-num-seqs caps concurrent decoding sequences and
# is the simplest mitigation against one tenant starving another. Set
# gpu-memory-utilization below 1.0 to leave headroom for the dev pod.
VLLM_MAX_NUM_SEQS=32
VLLM_GPU_MEMORY_UTILIZATION=0.85

# Shared API key. Treat as root-only secret material.
VLLM_API_KEY=${api_key}
EOF

chmod 0600 "${ENV_FILE}"
chown root:root "${ENV_FILE}"
