#!/usr/bin/env bash

# Exit on errors, unset vars, and failed pipelines.
set -euo pipefail

# Run from the script's directory so the ./output path is stable regardless
# of where the caller is.
cd "$(dirname "$0")"

IMAGE_NAME="${1:-gpu-bootc-host:latest}"
VM_NAME="${VM_NAME:-gpu-bootc-test}"

# --- SSH key detection ---
SSH_PUB_KEY_FILE="${SSH_PUB_KEY_FILE:-}"
if [ -z "${SSH_PUB_KEY_FILE}" ]; then
  for candidate in "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
    if [ -f "${candidate}" ]; then
      SSH_PUB_KEY_FILE="${candidate}"
      break
    fi
  done
fi

if [ -z "${SSH_PUB_KEY_FILE}" ] || [ ! -f "${SSH_PUB_KEY_FILE}" ]; then
  echo "ERROR: No SSH public key found." >&2
  echo "       Tried ~/.ssh/id_ed25519.pub and ~/.ssh/id_rsa.pub." >&2
  echo "       Generate one with: ssh-keygen -t ed25519" >&2
  echo "       Or set SSH_PUB_KEY_FILE=/path/to/key.pub and re-run." >&2
  exit 1
fi

SSH_PUB_KEY="$(cat "${SSH_PUB_KEY_FILE}")"
echo "=== Using SSH public key: ${SSH_PUB_KEY_FILE}"

# --- Fresh output directory ---
mkdir -p ./output
sudo rm -rf ./output/*

# --- Generate config.toml ---
# The OCI image is keyless; credentials are injected here into the qcow2 only.
CONFIG_FILE="./output/config.toml"
cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by build_vm.sh — do not edit.
# Injects the build host's SSH public key into root's authorized_keys on
# the produced qcow2. The OCI image itself remains keyless and shareable.
[[customizations.user]]
name = "root"
key = "${SSH_PUB_KEY}"
EOF

# --- Load image into root's container storage ---
echo "=== Loading ${IMAGE_NAME} into root container storage ==="
podman save "${IMAGE_NAME}" | sudo podman load

echo "=== Converting ${IMAGE_NAME} to qcow2 ==="
sudo podman run \
  --rm \
  --privileged \
  -v "$(pwd)/output:/output" \
  -v "$(pwd)/output/config.toml:/config.toml:ro" \
  -v /var/lib/containers/storage:/var/lib/containers/storage \
  quay.io/centos-bootc/bootc-image-builder:latest \
  --type qcow2 \
  --rootfs xfs \
  --config /config.toml \
  --local "localhost/${IMAGE_NAME}"

# --- Install disk into the libvirt storage pool ---
# QEMU runs as the system 'qemu' user and cannot read files under /home.
# /var/lib/libvirt/images is the default libvirt pool with proper qemu access.
echo "=== Installing VM disk into libvirt storage pool ==="
DISK_SRC="$(pwd)/output/qcow2/disk.qcow2"
DISK_DEST="/var/lib/libvirt/images/${VM_NAME}.qcow2"
sudo cp "${DISK_SRC}" "${DISK_DEST}"
sudo chown qemu:qemu "${DISK_DEST}"
echo "    Disk installed at ${DISK_DEST}"

echo ""
echo "=== Build complete ==="
echo "    Boot the VM with:  ./run_vm.sh"
