#!/usr/bin/env bash

# Exit on errors, unset vars, and failed pipelines.
set -euo pipefail

# Run from the script's directory so the ./output path is stable regardless
# of where the caller is.
cd "$(dirname "$0")"

IMAGE_NAME="${1:-gpu-bootc-host:latest}"
VM_NAME="${VM_NAME:-gpu-bootc-test}"
SSH_CONFIG="${HOME}/.ssh/config"

# --- SSH key detection ---
SSH_PUB_KEY_FILE="${SSH_PUB_KEY_FILE:-}"
if [ -z "${SSH_PUB_KEY_FILE}" ]; then
  for candidate in "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
    if [ -f "${candidate}" ]; then
      SSH_PUB_KEY_FILE="${candidate}"
      break
    fi
  done
fi

if [ -z "${SSH_PUB_KEY_FILE}" ] || [ ! -f "${SSH_PUB_KEY_FILE}" ]; then
  echo "ERROR: No SSH public key found." >&2
  echo "       Tried ~/.ssh/id_ed25519.pub and ~/.ssh/id_rsa.pub." >&2
  echo "       Generate one with: ssh-keygen -t ed25519" >&2
  echo "       Or set SSH_PUB_KEY_FILE=/path/to/key.pub and re-run." >&2
  exit 1
fi

SSH_PUB_KEY="$(cat "${SSH_PUB_KEY_FILE}")"
SSH_KEY_FILE="${SSH_PUB_KEY_FILE%.pub}"
echo "=== Using SSH public key: ${SSH_PUB_KEY_FILE}"

# --- Tear down any existing VM of the same name ---
echo "=== Removing any existing '${VM_NAME}' VM ==="
sudo virsh destroy  "${VM_NAME}" 2>/dev/null || true
sudo virsh undefine "${VM_NAME}" --nvram 2>/dev/null || true

# --- Fresh output directory ---
mkdir -p ./output
sudo rm -rf ./output/*

# --- Generate config.toml ---
# The OCI image is keyless; credentials are injected here into the qcow2 only.
CONFIG_FILE="./output/config.toml"
cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by run_bootc_vm.sh — do not edit.
# Injects the build host's SSH public key into root's authorized_keys on
# the produced qcow2. The OCI image itself remains keyless and shareable.
[[customizations.user]]
name = "root"
key = "${SSH_PUB_KEY}"
EOF

# --- Load image into root's container storage ---
echo "=== Loading $IMAGE_NAME into root container storage ==="
podman save "${IMAGE_NAME}" | sudo podman load

echo "=== Converting $IMAGE_NAME to qcow2 ==="
sudo podman run \
  --rm \
  --privileged \
  -v "$(pwd)/output:/output" \
  -v "$(pwd)/output/config.toml:/config.toml:ro" \
  -v /var/lib/containers/storage:/var/lib/containers/storage \
  quay.io/centos-bootc/bootc-image-builder:latest \
  --type qcow2 \
  --rootfs xfs \
  --config /config.toml \
  --local "localhost/$IMAGE_NAME"

# --- Install disk into the libvirt storage pool ---
# QEMU runs as the system 'qemu' user and cannot read files under /home.
# /var/lib/libvirt/images is the default libvirt pool with proper qemu access.
echo "=== Installing VM disk into libvirt storage pool ==="
DISK_SRC="$(pwd)/output/qcow2/disk.qcow2"
DISK_DEST="/var/lib/libvirt/images/${VM_NAME}.qcow2"
sudo cp "${DISK_SRC}" "${DISK_DEST}"
sudo chown qemu:qemu "${DISK_DEST}"
echo "    Disk installed at ${DISK_DEST}"

echo "=== Starting VM ==="

# --noautoconsole lets virt-install exit immediately after the domain starts
# so this script can continue to detect the IP and configure SSH.
# Attach manually any time with: sudo virsh console gpu-bootc-test
sudo virt-install \
  --name "${VM_NAME}" \
  --memory 16384 \
  --vcpus 8 \
  --disk path="${DISK_DEST}",format=qcow2,bus=virtio \
  --import \
  --os-variant fedora-unknown \
  --network network=default \
  --graphics none \
  --noautoconsole \
  --boot uefi

# --- After console detach: detect IP and wire up SSH alias ---
echo ""
echo "=== Detecting VM IP address ==="
VM_IP=""
for i in $(seq 1 30); do
  VM_IP=$(sudo virsh domifaddr "${VM_NAME}" 2>/dev/null \
    | awk '/ipv4/{print $4}' | cut -d/ -f1 | head -1)
  [ -n "${VM_IP}" ] && break
  echo "    waiting... (${i}/30)"
  sleep 2
done

if [ -z "${VM_IP}" ]; then
  echo ""
  echo "=== Could not detect VM IP automatically. ==="
  echo "    Run:  sudo virsh domifaddr ${VM_NAME}"
  echo "    Then: ssh root@<ip>"
  exit 0
fi

# Write/update a 'fedora-init' Host block in ~/.ssh/config so the user
# can connect with just 'ssh fedora-init' from any terminal. The block is
# replaced on every run so the IP stays current after rebuilds.
# StrictHostKeyChecking is disabled for this alias because the VM's host
# key changes on every rebuild — without this the user would get a
# "host key changed" warning after each ./run_bootc_vm.sh.
touch "${SSH_CONFIG}"
chmod 600 "${SSH_CONFIG}"
sed -i '/^# BEGIN fedora-init$/,/^# END fedora-init$/d' "${SSH_CONFIG}"
cat >> "${SSH_CONFIG}" <<EOF

# BEGIN fedora-init
Host fedora-init
    HostName ${VM_IP}
    User root
    IdentityFile ${SSH_KEY_FILE}
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
# END fedora-init
EOF

echo ""
echo "=== Access ==="
echo "    ssh fedora-init"
echo ""
echo "    (${VM_IP} | key: ${SSH_KEY_FILE})"
echo ""
echo "    To see the boot console:  sudo virsh console ${VM_NAME}"
echo "    To detach from console:   Ctrl+]"
